### ISSUE TITLE
如何开启日志

### ISSUE THREAD

**Issue by qinfengge** [xizixuejie/canal-spring#10]
如何开启日志呢？还有就是一定要配MQ吗
没配MQ没有任何日志，也没有任何效果
都是照着文档来的
![image](https://github.com/xizixuejie/canal-spring/assets/35164697/92b857d9-43f3-4812-946f-c58f8e11eac8)

**Comment by qinfengge** [comment]
server-mode要强制指定tcp才有效，即使它有默认值
![image](https://github.com/xizixuejie/canal-spring/assets/35164697/7b7f55df-5746-45ec-9c08-48b331a68006)

**Comment by xizixuejie** [comment]
新版本修改了这个问题，更新到0.0.6解决了
