### ISSUE TITLE
只是显示的配置了server和destination，默认应该是tcp方式消费，但消费时间还是有延迟

### ISSUE THREAD

**Issue by aitxiaogang** [xizixuejie/canal-spring#25]
canal.server=127.0.0.1:11111
canal.destination=example

默认还是有1S的等待时间，请问怎么取消等待

**Comment by aitxiaogang** [comment]
方便加一个你的联系方式吗，最好创建一个群可以沟通

**Comment by aitxiaogang** [comment]
![image](https://github.com/xizixuejie/canal-spring/assets/18614347/2ec6800d-297c-4e9a-ac23-80f82a911aa0)
我看源码里面使用TCP模式还是会等待

**Comment by xizixuejie** [comment]
canal.timeout = -1 

![image](https://github.com/xizixuejie/canal-spring/assets/58165062/54c2d2c5-34ad-4d4d-aae9-687c584177b2)

**Comment by xizixuejie** [comment]
建了个qq群，286331326
