### ISSUE TITLE
如果本地开发时没办法链接canal server,怎么设置能不影响SpringBoot的正常启动呢？

### ISSUE THREAD

**Issue by lyy2002** [xizixuejie/canal-spring#32]
如果本地开发时没办法拦截canal server,怎么设置能不影响SpringBoot的正常启动呢？
我现在每次要先把@EnableCanalListener()注释掉，然后才能启动。但打包的时候容易忘记开注释。。。。

**Comment by xizixuejie** [comment]
配置文件设置 `canal.server-mode` 为空，也不会启动监听

![image](https://github.com/xizixuejie/canal-spring/assets/58165062/fd4589ea-d040-46d0-a8fe-3bca6083a8f6)

**Comment by lyy2002** [comment]
> 配置文件设置 `canal.server-mode` 为空，也不会启动监听
> 
> ![image](https://private-user-images.githubusercontent.com/58165062/332699515-fd4589ea-d040-46d0-a8fe-3bca6083a8f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjY2NzEsIm5iZiI6MTcxNjM2NjM3MSwicGF0aCI6Ii81ODE2NTA2Mi8zMzI2OTk1MTUtZmQ0NTg5ZWEtZDA0MC00NmQwLWE4ZmUtM2JjYTYwODNhOGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA4MjYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MDI2MjVhNjJkNjNjNDBiZDdhNWM1MTViNzA1ZGZjOWY4MjViNGEwZGJhY2NmOTNjNWQ4MDNmNmNmODNkZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MWAzed3umEDCsftS6NGhwXK-qpYgK1M3k5EM92DAVkI)

Ok,可以了.多谢
