### ISSUE TITLE
继承问题

### ISSUE THREAD

**Issue by vanne-cc** [xizixuejie/canal-spring#34]
子类继承父类，在不想动父类的情况下，想添加@ColumnConvertor注解进行父类info字段的类型转换，给子类添加和父类一致的info字段，然后将@ColumnConvertor注解写在子类info字段上。  会报 Caused by: java.lang.IllegalStateException: Duplicate key info 错误。
请问这个有优化空间吗。

**Comment by xizixuejie** [comment]
v0.0.16 已修复
