### ISSUE TITLE
使用spring-context-indexer依赖时，出现重复bean的异常。

### ISSUE THREAD

**Issue by vanne-cn** [xizixuejie/canal-spring#35]
使用spring-context-indexer依赖时，CanalListenerScanner报了重复bean的异常。
![image](https://github.com/xizixuejie/canal-spring/assets/30721832/72e085d8-da84-47b4-9fe4-00d74a0c6029)
请问改成以下扫描方式，是否有影响呢。

![image](https://github.com/xizixuejie/canal-spring/assets/30721832/c438099e-d25e-4fde-8596-7cb077c4bf0a)

**Comment by xizixuejie** [comment]
没什么影响，能连上能接收到消息就行。

我试了一下，是自定义的 `@CanalListener` 注解上面加已经加了 `@Component` 注解的原因。

当时我是为了解决 #3 这个问题，强迫症看着有点难受😂，直接在 `@CanalListener` 上面加了个 `@Component`  [03a976fe](https://github.com/xizixuejie/canal-spring/commit/0d93c230b842d01c61428152f712aecf03a976fe
) ，但是这样的话 `CanalListenerRegistrar` 都没必要用了，好像有些不妥，我看看还是把这个去了吧，有需要的再自己加`@Component` 好了

**Comment by vanne-cn** [comment]
好的。☺
