### ISSUE TITLE
想关注确切的变化字段

### ISSUE THREAD

**Issue by vanne-cn** [xizixuejie/canal-spring#37]
![image](https://github.com/user-attachments/assets/c61baabb-87bb-48cf-9546-62e60880129f)
如果变化前的字段值为 NULL 或者  为""空串，由Map转成实体类后，是不是就无法确切的知道是哪个字段发生变化了。因为before获取到的字段值始终是null，有处理方案吗。

**Comment by xizixuejie** [comment]
v0.0.17 已支持
